### ISSUE TITLE
Feature request: alias support

### ISSUE THREAD

**Issue by davidandradeduarte** [sachaos/viddy#9] opened 2021-08-19 10:58 UTC
Hi,

Thank you for developing viddy!

I think one thing that could be a really good improvement over the current `watch` command is adding **support for aliases**.

Currently there's a bunch of work-arounds to get watch to work with aliases.

If viddy could add native support to use aliases, that would attract a lot of attention.

**Comment by Croissong** [comment] 2021-08-19 11:11
Duplicate of #2 i think ;)

**Closed** 2021-08-19 12:16 UTC

**Comment by davidandradeduarte** [comment] 2021-08-19 12:17
Yeah, it's the same feature request. My bad for not looking at the already open issues.
https://github.com/sachaos/viddy/issues/2
