### ISSUE TITLE
Arguments with spaces in watch command are incorrectly split

### ISSUE THREAD

**Issue by koterpillar** [sachaos/viddy#70] opened 2022-08-05 07:20 UTC
This command gives the tabular output with details:

```
$ bash -c 'ls -l'
total 0
-rw-r--r--. 1 user user 0 Aug  5 17:23 a
-rw-r--r--. 1 user user 0 Aug  5 17:23 b
-rw-r--r--. 1 user user 0 Aug  5 17:23 c
```

However, Viddy breaks it, and `-l` is passed to `bash`, not `ls`:

```shell
viddy bash -c 'ls -l'
```

![viddy output with just file names](https://user-images.githubusercontent.com/140276/183024635-908f8000-45e6-43a3-bb07-28880c6fc298.png)

This behavior is present in traditional `watch`, but I don't actually see a reason for it.

**Comment by koterpillar** [comment] 2022-08-05 09:53
Here the arguments are joined together, which causes the incorrect behavior if some arguments already contain spaces:

https://github.com/sachaos/viddy/blob/0ab3347/snapshot.go#L110

**Comment by phanirithvij** [comment] 2024-02-26 04:46
viddy "bash -c 'ls -l'"
watch "bash -c 'ls -l'"

**Comment by GianniBYoung** [comment] 2024-12-02 22:11
This seems like a non-issue that can be closed?

like @phanirithvij commented the quoting in the issue is incorrect.

**Comment by koterpillar** [comment] 2024-12-02 22:20
That is a workaround (until one needs more quotes in arguments) but I don't see how the current behavior is desirable.

**Comment by GianniBYoung** [comment] 2024-12-03 02:01
Correct me if I am wrong but viddy calls `sh -c` to run the commands given to it so with the above example you would get something like:

`viddy` calls `sh -c` which calls `bash -c` with the _arg_ of `ls -l`

However that's not the case because of how arguments are grouped.

In a regular session `sh -c bash -c ls -l` just drops you to a bash shell (only processes the first argument, 'bash') while `sh -c 'bash -c ls -l'` provides ls output ignoring the `-l` flag.

To achieve the result you are looking for you still need proper quoting: `sh -c "bash -c 'ls -l'"`

This feels more like improper usage than undesirable behavior. There needs to be some way to differentiate/group together commands and options which is best achieved by proper quoting.

 This screen shot shows how drastically quoting can effect things:
 
![image](https://github.com/user-attachments/assets/dabdc444-e5bd-4677-888e-c95164acdbda)

**Comment by koterpillar** [comment] 2024-12-03 04:20
> arguments are grouped

This is the core of my problem.

* `viddy bash -c 'ls -l'` provides 3 arguments to `viddy` ✅
* Viddy merges the 3 arguments together and passes them as one to `sh -c`: `sh -c 'bash -c ls -l'` 💥

I argue that this transformation never makes sense, and instead Viddy should quote the arguments for me (see e.g. [shlex.quote](https://docs.python.org/3/library/shlex.html#shlex.quote)).

I know I can (with difficulty if nesting quotes inside quotes) work around this behaviour, but it makes the use case of "I have the command; now prepend `viddy` in front" much harder and doesn't have any benefits that I can see.

**Comment by GianniBYoung** [comment] 2024-12-03 05:23
I better see where you are coming from now and I think it branches into different patterns of thought.

There is convenience to being able to pass in a _block_ but this shifts complexity onto the program and goes against the natural patterns of the underlying tool and typical shell usage.

> the use case of "I have the command; now prepend viddy in front" much harder and doesn't have any benefits that I can see.

A potential issue/misstep here I see is with how shells expand out variables. Without quoting Variables are expanded **before** being passed to the command (viddy here).

This could lead to a situation where the viddy command is referencing a variable derived from your top-level shell's environment instead of being expanded by viddy itself.

**Comment by sachaos** [comment] 2024-12-04 14:07
@koterpillar @GianniBYoung Thank you all! Sorry for the late response.

As an alternative workaround, you can use the -x, --exec option.
With this option, arguments are executed directly without being passed to bash -c.
This behavior is the same as that of the watch command.

Therefore, commands like viddy -x bash -c 'ls -l' or watch -x bash -c 'ls -l' may work as expected without needing quotes.

I believe compatibility with watch is important.

**Comment by sachaos** [comment] 2024-12-05 06:13
I would like to close this issue.
If anyone has the problem, feel free to reopen this.

**Closed by sachaos** 2024-12-05 06:13 UTC
