### ISSUE TITLE
Why can't I select text with my mouse?

### ISSUE THREAD

**Issue by mosheavni** [sachaos/viddy#76] opened 2022-09-05 06:47 UTC
Using iTerm2 on macOS 12.4, shell is zsh
With `watch` command I can select text and copy it to my clipboard, but on viddy I cannot select anything.
Is this intended?
Thanks.

**Comment by whites11** [comment] 2022-10-21 13:03
Duplicate of https://github.com/sachaos/viddy/issues/74

**Comment by mosheavni** [comment] 2023-08-23 14:10
> That is for me the only blocker to not constantly use viddy... Beside that its great! I like the "Diff" feature most!
> 
> I would as well be interested in the technical background of this...

yeah me and my co-workers ditched viddy because of that.

**Comment by nickma82** [comment] 2023-08-24 06:45
@sachaos do you have any insight?
Maybe someone else is willing to fix it?

**Comment by sachaos** [comment] 2023-08-24 07:43
@nickma82 It works well in my environment.
I'm using Mac 11.5.2 and iTerm 3.4.19.

**Comment by whites11** [comment] 2023-08-24 07:52
> @nickma82 It works well in my environment. I'm using Mac 11.5.2 and iTerm 3.4.19.

arch linux, konsole 23.04.3, viddy 0.3.6 unfortunately it does not work

**Comment by sachaos** [comment] 2023-08-24 08:11
I believe it's probably due to the behavior of tview that viddy is using.
Is it the same with other applications made with tview?
https://github.com/rivo/tview

**Comment by whites11** [comment] 2023-08-24 08:34
> I believe it's probably due to the behavior of tview that viddy is using. Is it the same with other applications made with tview? https://github.com/rivo/tview

interestingly enough, I tried one of the apps listed in tviews' repo (`k9s`) and I can select text and copy paste at will

**Comment by sachaos** [comment] 2023-08-24 09:07
@nickma82 @whites11 Thank you.
Thank you. I might have been able to find the problem.
I've disabled mouse feature of tview.
Could you try with building latest master?
https://github.com/sachaos/viddy/pull/93

**Comment by whites11** [comment] 2023-08-24 09:24
> @nickma82 @whites11 Thank you. Thank you. I might have been able to find the problem. I've disabled mouse feature of tview. Could you try with building latest master? #93

It works fantastically well <3

**Comment by nickma82** [comment] 2023-08-24 10:16
This works, thanks a lot!

**Comment by whites11** [comment] 2023-08-24 10:52
Thanks a lot for solving this!!!!

**Closed** 2023-08-24 10:58 UTC
